/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFVAR = 5;
  /** RegularExpression Id. */
  int DEFPROC = 6;
  /** RegularExpression Id. */
  int MOVE = 7;
  /** RegularExpression Id. */
  int PUT = 8;
  /** RegularExpression Id. */
  int PICK = 9;
  /** RegularExpression Id. */
  int POP = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int GO = 12;
  /** RegularExpression Id. */
  int WALK = 13;
  /** RegularExpression Id. */
  int JUMP = 14;
  /** RegularExpression Id. */
  int LEAP = 15;
  /** RegularExpression Id. */
  int TURN = 16;
  /** RegularExpression Id. */
  int TURNTO = 17;
  /** RegularExpression Id. */
  int DROP = 18;
  /** RegularExpression Id. */
  int GET = 19;
  /** RegularExpression Id. */
  int GRAB = 20;
  /** RegularExpression Id. */
  int LETGO = 21;
  /** RegularExpression Id. */
  int NOP = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int WHILE = 25;
  /** RegularExpression Id. */
  int REPEAT = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int FACING = 28;
  /** RegularExpression Id. */
  int CAN = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int BALLOONS = 31;
  /** RegularExpression Id. */
  int CHIPS = 32;
  /** RegularExpression Id. */
  int idname = 33;
  /** RegularExpression Id. */
  int NUM = 34;
  /** RegularExpression Id. */
  int FRONT = 35;
  /** RegularExpression Id. */
  int RIGHT = 36;
  /** RegularExpression Id. */
  int LEFT = 37;
  /** RegularExpression Id. */
  int BACK = 38;
  /** RegularExpression Id. */
  int AROUND = 39;
  /** RegularExpression Id. */
  int NORTH = 40;
  /** RegularExpression Id. */
  int SOUTH = 41;
  /** RegularExpression Id. */
  int WEST = 42;
  /** RegularExpression Id. */
  int EAST = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"defVar\"",
    "\"defProc\"",
    "\"move\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"Hop\"",
    "\"Go\"",
    "\"walk\"",
    "\"jump\"",
    "\"leap\"",
    "\"turn\"",
    "\"turnto\"",
    "\"drop\"",
    "\"get\"",
    "\"grab\"",
    "\"letGo\"",
    "\"nop\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\"times\"",
    "\"facing\"",
    "\"can\"",
    "\"not\"",
    "\"balloons\"",
    "\"chips\"",
    "<idname>",
    "<NUM>",
    "\"front\"",
    "\"right\"",
    "\"left\"",
    "\"back\"",
    "\"around\"",
    "\"north\"",
    "\"south\"",
    "\"west\"",
    "\"east\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\";\"",
  };

}
